/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppCandidatesRouteImport } from './routes/_app.candidates'
import { Route as AppInterviewsRouteImport } from './routes/_app.interviews'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as OOrgSlugIndexRouteImport } from './routes/o.$orgSlug.index'
import { Route as OOrgSlugJobsJobIdRouteImport } from './routes/o.$orgSlug.jobs.$jobId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const OOrgSlugIndexRoute = OOrgSlugIndexRouteImport.update({
  id: '/o/$orgSlug/',
  path: '/o/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrgSlugJobsJobIdRoute = OOrgSlugJobsJobIdRouteImport.update({
  id: '/o/$orgSlug/jobs/$jobId',
  path: '/o/$orgSlug/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/applications': typeof AppApplicationsRoute
  '/candidates': typeof AppCandidatesRoute
  '/interviews': typeof AppInterviewsRoute
  '/jobs': typeof AppJobsRoute
  '/settings': typeof AppSettingsRoute
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
  '/o/$orgSlug/jobs/$jobId': typeof OOrgSlugJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/applications': typeof AppApplicationsRoute
  '/candidates': typeof AppCandidatesRoute
  '/interviews': typeof AppInterviewsRoute
  '/jobs': typeof AppJobsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/o/$orgSlug': typeof OOrgSlugIndexRoute
  '/o/$orgSlug/jobs/$jobId': typeof OOrgSlugJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/candidates': typeof AppCandidatesRoute
  '/_app/interviews': typeof AppInterviewsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/o/$orgSlug/': typeof OOrgSlugIndexRoute
  '/o/$orgSlug/jobs/$jobId': typeof OOrgSlugJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/applications'
    | '/candidates'
    | '/interviews'
    | '/jobs'
    | '/settings'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/applications'
    | '/candidates'
    | '/interviews'
    | '/jobs'
    | '/settings'
    | '/'
    | '/o/$orgSlug'
    | '/o/$orgSlug/jobs/$jobId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/applications'
    | '/_app/candidates'
    | '/_app/interviews'
    | '/_app/jobs'
    | '/_app/settings'
    | '/_app/'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OOrgSlugIndexRoute: typeof OOrgSlugIndexRoute
  OOrgSlugJobsJobIdRoute: typeof OOrgSlugJobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates': {
      id: '/_app/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews': {
      id: '/_app/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/o/$orgSlug/': {
      id: '/o/$orgSlug/'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof OOrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orgSlug/jobs/$jobId': {
      id: '/o/$orgSlug/jobs/$jobId'
      path: '/o/$orgSlug/jobs/$jobId'
      fullPath: '/o/$orgSlug/jobs/$jobId'
      preLoaderRoute: typeof OOrgSlugJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppInterviewsRoute: typeof AppInterviewsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppCandidatesRoute: AppCandidatesRoute,
  AppInterviewsRoute: AppInterviewsRoute,
  AppJobsRoute: AppJobsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OOrgSlugIndexRoute: OOrgSlugIndexRoute,
  OOrgSlugJobsJobIdRoute: OOrgSlugJobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
